In [1]:
import numpy as n
import matplotlib.pyplot as plt

In [2]:
simple_array_no_n = [[1,2,3],[4,5,6],[7,8,9]]

In [3]:
type(simple_array_no_n)

list

In [4]:
print(simple_array_no_n)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [5]:
# second row and last column
# 2x3 in real -> 1x2 in program
# last element of 2nd row 
simple_array_no_n[1][-1]

6

In [6]:
simple_array_n = n.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
type(simple_array_n)

numpy.ndarray

In [8]:
print(simple_array_n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
simple_array_n[1][-1]

6

In [10]:
float_array = n.array([[1,2,3],[4,5,6]], dtype='float')

In [11]:
type(float_array)

numpy.ndarray

In [12]:
print(float_array)

[[1. 2. 3.]
 [4. 5. 6.]]


In [13]:
for i in float_array[0]:
    print(type(i))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [14]:
float_array = n.array([[1,2,3],[4,5,6]], dtype='float32')

In [15]:
print(float_array)

[[1. 2. 3.]
 [4. 5. 6.]]


In [16]:
for i in float_array[0]:
    print(type(i))

<class 'numpy.float32'>
<class 'numpy.float32'>
<class 'numpy.float32'>


#### <p style="color:cyan;">float32 and float64 explained ['here'](https://stackoverflow.com/a/52804163/10582082)</p>

In [19]:
complex_array = n.array([[1,2,3],[4,5,6]], dtype='complex')

In [20]:
for i in complex_array[0]:
    print(type(i))

<class 'numpy.complex128'>
<class 'numpy.complex128'>
<class 'numpy.complex128'>


In [21]:
print(complex_array)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [22]:
complex_array.shape

(2, 3)

In [24]:
type(complex_array)

numpy.ndarray

### <p style="color:RED;"> ZEROs and ONEs </p>

In [39]:
zeros  = n.zeros( (3,3) )

In [40]:
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [41]:
for i in zeros[0]:
    print(type(i))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [42]:
zeros_int_32  = n.zeros( (3,3) , dtype = n.int32) #int64?

In [43]:
for i in zeros_int_32[0]:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [44]:
print(zeros_int_32)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [48]:
ones = n.ones( (3,3) )

In [64]:
for i in ones[0]:
    print(type(i))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


### <p style="color:RED;"> Arange and shape(reshape) </p>

In [65]:
arange_array = n.arange(1,9)

In [66]:
print(arange_array)

[1 2 3 4 5 6 7 8]


In [68]:
reshaped = arange_array.reshape(2,4)

In [69]:
type(reshaped)

numpy.ndarray

In [70]:
print(reshaped)

[[1 2 3 4]
 [5 6 7 8]]


In [80]:
reshaped[:]= n.float64(0)

In [81]:
print(reshaped)

[[0 0 0 0]
 [0 0 0 0]]


In [82]:
arange_one = n.arange(start=0,stop=9,step=1)

In [83]:
arange_two = n.arange(10,19)

In [84]:
print(arange_one)
print(arange_two)

[0 1 2 3 4 5 6 7 8]
[10 11 12 13 14 15 16 17 18]


In [85]:
array_three = arange_one + arange_two

In [86]:
print(array_three)

[10 12 14 16 18 20 22 24 26]


In [87]:
array_three.reshape(3,3)

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

In [88]:
array_dot = arange_one.dot(arange_two)
print(array_dot)

564


### <p style="color:RED;"> Transpose or $A^{-1}$ of a matrix </p>

In [89]:
small_array = n.array([[2,4,8],[3,6,12]])
small_array

array([[ 2,  4,  8],
       [ 3,  6, 12]])

In [90]:
small_array.transpose()

array([[ 2,  3],
       [ 4,  6],
       [ 8, 12]])